### ISSUE TITLE
Support DevTool

### ISSUE THREAD

**Issue by kota65535** [HriBB/react-paper-bindings#10]
Thank you for creating this great library!
Is there any plan for making paper relevant elements visible in DevTool to improve development experience?
AFAIK, `Reconciler` class has `injectIntoDevTools` method to do that.

**Comment by kota65535** [comment]
According to this [tutorial](https://github.com/nitin42/Making-a-custom-React-renderer/blob/master/part-one.md), I tried to add `injectIntoDevTools` to `View#render` method.
Layer, Circle, Tool element appears in DevTool, but when I continue to add Circle, it shows the message "Node was deleted" in every two elements.

This is the snapshot.
![image](https://user-images.githubusercontent.com/10975834/34485935-7b55f612-f010-11e7-8fa1-738a8c3ce27e.png)

**Comment by HriBB** [comment]
@kota65535 I managed to reproduce this issue. The reason for "Node was deleted" message may be [this piece of code](https://github.com/HriBB/react-paper-bindings/blob/master/demo/src/Paper/hoc/withCircleTool.js#L12-L24). I'm investigating the side effects now.

Not really sure yet what's happening. Could be a bug in PaperRenderer. The API has changed a lot since the beta, maybe I missed something when upgrading.

**Comment by HriBB** [comment]
Should I add `injectIntoDevTools` into the bundle?

```
render() {
    const { className, canvasProps } = this.props
    PaperRenderer.injectIntoDevTools({
      bundleType: 1, // 0 for PROD, 1 for DEV
      version: '0.1.0', // version for your renderer
      rendererPackageName: 'paper-renderer', // package name
      findHostInstanceByFiber: PaperRenderer.findHostInstance // host instance (root)
    })
    return (
      <canvas
        ref={ref => this.canvas = ref}
        {...canvasProps}
        className={className}
        onWheel={this.onWheel}
        onDoubleClick={this.onDoubleClick}
      />
    )
  }
```

**Comment by kota65535** [comment]
Yes, that is what I did in the comment above.
This method seems to work only when the devtool is active, so no performance issue.

**Comment by kota65535** [comment]
Close this issue because #13 has been merged.
