### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by swrd06bp** [HriBB/react-paper-bindings#7]
When I run the application I have this error, could you let me know if I am missing something?

> __webpack_require__.i(...) is not a function
(anonymous function)
/Users/Projects/React/react-paper-bindings/dist/PaperRenderer.js:179
  176 |   }
  177 | }
  178 | 
  179 | var PaperRenderer = ReactFiberReconciler({
  180 |   appendChild: function appendChild(parentInstance, child) {
  181 |     if (child.parentNode === parentInstance) {
  182 |       child.remove();
View compiled
   2 stack frames were collapsed.
(anonymous function)
/Users/Projects/React/react-paper-bindings/dist/View.js:1
  1 | var _jsxFileName = 'src/View.js';
  2 | 
  3 | var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();
  4 | 
View compiled
 2 stack frames were collapsed.
Object.defineProperty.value
/Users/Projects/React/react-paper-bindings/dist/index.js:1
 1 | import TYPES from './types';
  2 | import View from './View';
  3 | 
  4 | var CIRCLE = TYPES.CIRCLE,
View compiled
15 stack frames were collapsed.
>

**Comment by HriBB** [comment]
Hey @swrd06bp

Not 100% sure because it's late and I need to go to bed, but you probably need a custom build of `react-dom` that exports `ReactFiberReconciler`. This is needed until facebook releases `ReactFiberReconciler` https://github.com/facebook/react/issues/9103

Quick Instructions

Clone [react](https://github.com/facebook/react) repo
```bash
git clone https://github.com/facebook/react.git
cd react
npm install
```
Change `ReactDOMFiberEntry.js`
```diff
--- a/src/renderers/dom/fiber/ReactDOMFiberEntry.js
+++ b/src/renderers/dom/fiber/ReactDOMFiberEntry.js
@@ -729,6 +729,8 @@ var ReactDOMFiber = {
 
   findDOMNode: findDOMNode,
 
+  ReactFiberReconciler: ReactFiberReconciler,
+
   unstable_createPortal(
     children: ReactNodeList,
     container: DOMContainer,
```
Run
```bash
npm run build
cd build/packages/react
npm link
cd ../react-dom
npm link
```
Then in `react-paper-bindings`
```bash
npm link react react-dom
```

**Comment by HriBB** [comment]
Let me know if this is the problem ;)

**Comment by abhishiv** [comment]
Hey @HriBB thanks for the great work!

Just a question why is manually building necessary? Can't you just require `react-dom/lib/ReactFiberReconciler.js`?

**Comment by abhishiv** [comment]
Just found out, by chance the version I was on `react-dom@16.0.0-alpha.6` the last one with a lib folder and this export. Hope facebook/react#9103 is fixed soon!

**Comment by psychobolt** [comment]
As an alternative, you can use the [react-fiber-exports](https://www.npmjs.com/package/react-fiber-export) package.

I've tested it out with the demo and it seems to work fine. Needs some webpack configuration to minify the package for deployment though.

**Comment by maxtoken** [comment]
@psychobolt May I know the complete steps with react-fiber-export alternative?

**Comment by psychobolt** [comment]
react-reconciler is released as a npm package since React 16.1.  I would recommend upgrading React to 16.1 and installing the react-reconciler package. If you want to use react-fiber-export (compatible with React 16), all you need to do is install the package and change the import [line](https://github.com/HriBB/react-paper-bindings/blob/master/src/PaperRenderer.js#L1). You should change the import line regardless of which package you intend to use.

**Comment by HriBB** [comment]
Hopefully I can find some time during the weekend and do this ;)

**Comment by maxtoken** [comment]
Thanks @psychobolt and @HriBB ! Finally I could start the demo. But when using the Pen, Circle and Rectangle tools, below similar errors occurred:

![screen shot 2017-11-28 at 15 07 04](https://user-images.githubusercontent.com/12880054/33306579-16d3c6a2-d44e-11e7-982f-a7be8838e815.png)

**Comment by HriBB** [comment]
Hey, I was I a hurry when I published it, will fix the problems in the following days 😉

**Comment by HriBB** [comment]
Should be fixed now!
